workflows:
  android-simple:
    name: Simple Android Build
    environment:
      flutter: stable
    scripts:
      - flutter pub get
      - flutter packages pub run build_runner build --delete-conflicting-outputs
      - flutter build apk --release --no-shrink
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
